server:
  address: 0.0.0.0
  port: ${PORT:8080}
spring:
  profiles.active: ${ACTIVE_PROFILE:dev}
logging:
  level:
    org.springframework.web: DEBUG
    ru.javazen.telegram.bot: DEBUG
    org.hibernate: DEBUG
---
credential:
  telegram:
    name: ${TELEGRAM_BOT_NAME:alina_coursework_bot}
    token: ${TELEGRAM_BOT_TOKEN:573259579:AAFFZk1hTuibxIR5rmbzeL1bKxwCalMbXXM}
  google:
    apikey: ${GOOGLE_API_KEY:}
bot:
  url: ${SELF_URL:http://localhost:8080/}
http:
  proxy:
    url: ${PROXY_URL:http://igor:RKN_shall_not_pass@javazen.ru:8090}